import {CharacterDetail} from '@type/entities/character';

export const characterDetailDatas: CharacterDetail[] = [
  {
    id: 1,
    name: '플로라 하츄핑2',
    imageUrl: require('@assets/images/characters/img_aaping.png'),
    like: true,
    nameOrigin: '하트 + 츄',
    item: '향수(3기)',
    color: 'pink',
    gender: 'female',
    generation: '<사랑의 향기>(3기 향수)',
    magic:
      '향수를 뿌려서 상대 공격을 막을 수 있으며 대상을 향기에 취하게 만들 수 있다',
    hobby: ['로미와 함께 있는 모든 순간'],
    hate: ['억지로 잠을 깨우는 것', '갑자기 깜짝 놀라게 하는 것'],
    favoriteFood: ['생크림 딸기 케이크', '딸기'],
    hateFood: ['신맛이 나는 모든 것'],
  },
  {
    id: 2,
    name: '플로라 하츄핑2',
    imageUrl: require('@assets/images/characters/img_aaping.png'),
    like: true,
    nameOrigin: '하트 + 츄',
    item: '향수(3기)',
    color: 'pink',
    gender: 'female',
    generation: '<사랑의 향기>(3기 향수)',
    magic:
      '향수를 뿌려서 상대 공격을 막을 수 있으며 대상을 향기에 취하게 만들 수 있다',
    hobby: ['로미와 함께 있는 모든 순간'],
    hate: ['억지로 잠을 깨우는 것', '갑자기 깜짝 놀라게 하는 것'],
    favoriteFood: ['생크림 딸기 케이크', '딸기'],
    hateFood: ['신맛이 나는 모든 것'],
  },
  {
    id: 3,
    name: '플로라 하츄핑2',
    imageUrl: require('@assets/images/characters/img_aaping.png'),
    like: true,
    nameOrigin: '하트 + 츄',
    item: '향수(3기)',
    color: 'pink',
    gender: 'female',
    generation: '<사랑의 향기>(3기 향수)',
    magic:
      '향수를 뿌려서 상대 공격을 막을 수 있으며 대상을 향기에 취하게 만들 수 있다',
    hobby: ['로미와 함께 있는 모든 순간'],
    hate: ['억지로 잠을 깨우는 것', '갑자기 깜짝 놀라게 하는 것'],
    favoriteFood: ['생크림 딸기 케이크', '딸기'],
    hateFood: ['신맛이 나는 모든 것'],
  },
  {
    id: 4,
    name: '플로라 하츄핑2',
    imageUrl: require('@assets/images/characters/img_aaping.png'),
    like: true,
    nameOrigin: '하트 + 츄',
    item: '향수(3기)',
    color: 'green',
    gender: 'female',
    generation: '<사랑의 향기>(3기 향수)',
    magic:
      '향수를 뿌려서 상대 공격을 막을 수 있으며 대상을 향기에 취하게 만들 수 있다',
    hobby: ['로미와 함께 있는 모든 순간'],
    hate: ['억지로 잠을 깨우는 것', '갑자기 깜짝 놀라게 하는 것'],
    favoriteFood: ['생크림 딸기 케이크', '딸기'],
    hateFood: ['신맛이 나는 모든 것'],
  },
  {
    id: 5,
    name: '플로라 하츄핑2',
    imageUrl: require('@assets/images/characters/img_aaping.png'),
    like: true,
    nameOrigin: '하트 + 츄',
    item: '향수(3기)',
    color: 'pink',
    gender: 'female',
    generation: '<사랑의 향기>(3기 향수)',
    magic:
      '향수를 뿌려서 상대 공격을 막을 수 있으며 대상을 향기에 취하게 만들 수 있다',
    hobby: ['로미와 함께 있는 모든 순간'],
    hate: ['억지로 잠을 깨우는 것', '갑자기 깜짝 놀라게 하는 것'],
    favoriteFood: ['생크림 딸기 케이크', '딸기'],
    hateFood: ['신맛이 나는 모든 것'],
  },
];
